module.exports = {
  extends: ["@commitlint/config-conventional"],
  ignores: [
    (message) => /^Merge /.test(message),
    (message) => /^initial commit$/i.test(message.trim()),
  ],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "build",
        "chore",
        "ci",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "test",
      ],
    ],
    "type-case": [2, "always", "lower-case"],
    "scope-case": [2, "always", "lower-case"],
    "scope-empty": [0],
    "scope-enum": [
      2,
      "always",
      [
        "account-links",
        "admin",
        "admin-console",
        "audit",
        "auth",
        "browser",
        "ci",
        "client",
        "claims",
        "compliance",
        "conformance",
        "config",
        "core",
        "crates",
        "db",
        "deps",
        "devshell",
        "design",
        "docker",
        "docs",
        "e2e",
        "extraction",
        "ffi",
        "federation",
        "fstar",
        "handoff",
        "infra",
        "issuer",
        "jose",
        "kani",
        "lint",
        "launch",
        "management",
        "management-client",
        "markdown",
        "nix",
        "oauth",
        "oidc",
        "packages",
        "perf",
        "policy",
        "proofs",
        "primary-authority",
        "providers",
        "readme",
        "roadmap",
        "release",
        "runtime",
        "scripts",
        "sdk",
        "security",
        "server",
        "spec",
        "stack",
        "storybook",
        "tamarin",
        "tests",
        "tooling",
        "ui",
        "verification",
      ],
    ],
    "subject-case": [0],
    "subject-full-stop": [2, "never", "."],
    "header-max-length": [2, "always", 72],
    "body-max-line-length": [2, "always", 100],
    "footer-max-line-length": [2, "always", 100],
    "body-leading-blank": [1, "always"],
    "footer-leading-blank": [1, "always"],
  },
};
