/* Auto-generated by run_jose_lowstar.sh for Stack module
* KaRaMeL -skip-compilation doesn't generate internal/ directory.
* This stub provides the minimal includes needed by Jose_LowStar_Json_Stack.c
*/

#ifndef __INTERNAL_FSTAR_H
#define __INTERNAL_FSTAR_H

#include "FStar_UInt_8_16_32_64.h"
#include "krmllib.h"

#endif /* __INTERNAL_FSTAR_H */
