/*
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /nix/store/yl5jym98klm1y40y6lnsf47c3scqj8dd-karamel-2025-10-08/bin/krml -tmpdir artifacts/karamel -bundle Jose.LowStar.Json.Stack=Jose.LowStar.* -skip-compilation /tmp/tmp.M8KhzUXtzz/out.krml -warn-error -9
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef Jose_Context_H
#define Jose_Context_H

#include "krmllib.h"

typedef krml_checked_int_t Jose_Context_jose_context;

extern krml_checked_int_t Jose_Context_default_context;

krml_checked_int_t Jose_Context_make_context(krml_checked_int_t max_len);


#define Jose_Context_H_DEFINED
#endif /* Jose_Context_H */
