/*
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /nix/store/yl5jym98klm1y40y6lnsf47c3scqj8dd-karamel-2025-10-08/bin/krml -tmpdir artifacts/karamel -bundle Jose.LowStar.Json.Stack=Jose.LowStar.* -skip-compilation /tmp/tmp.M8KhzUXtzz/out.krml -warn-error -9
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "Jose_Context.h"

krml_checked_int_t Jose_Context_default_context = (krml_checked_int_t)4096;

krml_checked_int_t Jose_Context_make_context(krml_checked_int_t max_len)
{
  return max_len;
}
