/*
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /nix/store/yl5jym98klm1y40y6lnsf47c3scqj8dd-karamel-2025-10-08/bin/krml -tmpdir artifacts/karamel -bundle Jose.LowStar.Json.Stack=Jose.LowStar.* -skip-compilation /tmp/tmp.M8KhzUXtzz/out.krml -warn-error -9
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef Jose_LowStar_Json_Stack_H
#define Jose_LowStar_Json_Stack_H

#include "krmllib.h"

#define Jose_LowStar_Json_Stack_JsonValueString 0
#define Jose_LowStar_Json_Stack_JsonValueNull 1

typedef uint8_t Jose_LowStar_Json_Stack_json_value_kind;

bool
Jose_LowStar_Json_Stack_uu___is_JsonValueString(
  Jose_LowStar_Json_Stack_json_value_kind projectee
);

bool
Jose_LowStar_Json_Stack_uu___is_JsonValueNull(
  Jose_LowStar_Json_Stack_json_value_kind projectee
);

typedef struct Jose_LowStar_Json_Stack_json_member_c_s
{
  uint8_t *key_buf;
  krml_checked_int_t key_len;
  Jose_LowStar_Json_Stack_json_value_kind value_kind;
  uint8_t *value_buf;
  krml_checked_int_t value_len;
}
Jose_LowStar_Json_Stack_json_member_c;

typedef struct Jose_LowStar_Json_Stack_bytes_block_s
{
  uint8_t *buf;
  uint32_t len;
}
Jose_LowStar_Json_Stack_bytes_block;

#define Jose_LowStar_Json_Stack_BytesBlockNone 0
#define Jose_LowStar_Json_Stack_BytesBlockSome 1

typedef uint8_t Jose_LowStar_Json_Stack_bytes_block_option_tags;

typedef struct Jose_LowStar_Json_Stack_bytes_block_option_s
{
  Jose_LowStar_Json_Stack_bytes_block_option_tags tag;
  Jose_LowStar_Json_Stack_bytes_block _0;
}
Jose_LowStar_Json_Stack_bytes_block_option;

bool
Jose_LowStar_Json_Stack_uu___is_BytesBlockNone(
  Jose_LowStar_Json_Stack_bytes_block_option projectee
);

bool
Jose_LowStar_Json_Stack_uu___is_BytesBlockSome(
  Jose_LowStar_Json_Stack_bytes_block_option projectee
);

typedef struct Jose_LowStar_Json_Stack_json_member_u32_s
{
  Jose_LowStar_Json_Stack_bytes_block u32_key;
  Jose_LowStar_Json_Stack_json_value_kind u32_value_kind;
  Jose_LowStar_Json_Stack_bytes_block_option u32_value;
}
Jose_LowStar_Json_Stack_json_member_u32;

extern uint8_t *Jose_LowStar_Json_Stack_malloc_bytes(krml_checked_int_t len);

void
Jose_LowStar_Json_Stack_copy_bytes_u32_aux(
  uint8_t *src,
  uint8_t *dst,
  uint32_t len32,
  uint32_t idx32
);

Jose_LowStar_Json_Stack_bytes_block
Jose_LowStar_Json_Stack_read_bytes_with_bound_u32(uint8_t *buf, uint32_t len32);

Jose_LowStar_Json_Stack_json_member_u32
Jose_LowStar_Json_Stack_read_member_u32_stack(Jose_LowStar_Json_Stack_json_member_c m);

typedef struct Prims_list__Jose_LowStar_Json_Stack_json_member_u32_s
Prims_list__Jose_LowStar_Json_Stack_json_member_u32;

#define Prims_Nil 0
#define Prims_Cons 1

typedef uint8_t Prims_list__Jose_LowStar_Json_Stack_json_member_u32_tags;

typedef struct Prims_list__Jose_LowStar_Json_Stack_json_member_u32_s
{
  Prims_list__Jose_LowStar_Json_Stack_json_member_u32_tags tag;
  Jose_LowStar_Json_Stack_json_member_u32 hd;
  Prims_list__Jose_LowStar_Json_Stack_json_member_u32 *tl;
}
Prims_list__Jose_LowStar_Json_Stack_json_member_u32;

extern Prims_list__Jose_LowStar_Json_Stack_json_member_u32
*Jose_LowStar_Json_Stack_collect_members_u32_stack_aux(
  Jose_LowStar_Json_Stack_json_member_c *members,
  uint32_t count32,
  uint32_t idx32
);

Prims_list__Jose_LowStar_Json_Stack_json_member_u32
*Jose_LowStar_Json_Stack_collect_members_u32_stack(
  Jose_LowStar_Json_Stack_json_member_c *members,
  uint32_t count32
);


#define Jose_LowStar_Json_Stack_H_DEFINED
#endif /* Jose_LowStar_Json_Stack_H */
