/*
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /nix/store/yl5jym98klm1y40y6lnsf47c3scqj8dd-karamel-2025-10-08/bin/krml -tmpdir artifacts/karamel -bundle Jose.LowStar.Json.Stack=Jose.LowStar.* -skip-compilation /tmp/tmp.M8KhzUXtzz/out.krml -warn-error -9
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "Jose_LowStar_Json_Stack.h"

#include "internal/FStar.h"

bool
Jose_LowStar_Json_Stack_uu___is_JsonValueString(
  Jose_LowStar_Json_Stack_json_value_kind projectee
)
{
  switch (projectee)
  {
    case Jose_LowStar_Json_Stack_JsonValueString:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool
Jose_LowStar_Json_Stack_uu___is_JsonValueNull(
  Jose_LowStar_Json_Stack_json_value_kind projectee
)
{
  switch (projectee)
  {
    case Jose_LowStar_Json_Stack_JsonValueNull:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool
Jose_LowStar_Json_Stack_uu___is_BytesBlockNone(
  Jose_LowStar_Json_Stack_bytes_block_option projectee
)
{
  if (projectee.tag == Jose_LowStar_Json_Stack_BytesBlockNone)
    return true;
  else
    return false;
}

bool
Jose_LowStar_Json_Stack_uu___is_BytesBlockSome(
  Jose_LowStar_Json_Stack_bytes_block_option projectee
)
{
  if (projectee.tag == Jose_LowStar_Json_Stack_BytesBlockSome)
    return true;
  else
    return false;
}

void
Jose_LowStar_Json_Stack_copy_bytes_u32_aux(
  uint8_t *src,
  uint8_t *dst,
  uint32_t len32,
  uint32_t idx32
)
{
  if (idx32 < len32)
  {
    uint8_t byte = src[idx32];
    dst[idx32] = byte;
    Jose_LowStar_Json_Stack_copy_bytes_u32_aux(src, dst, len32, idx32 + 1U);
  }
}

Jose_LowStar_Json_Stack_bytes_block
Jose_LowStar_Json_Stack_read_bytes_with_bound_u32(uint8_t *buf, uint32_t len32)
{
  uint8_t *dst = Jose_LowStar_Json_Stack_malloc_bytes(FStar_UInt32_v(len32));
  Jose_LowStar_Json_Stack_copy_bytes_u32_aux(buf, dst, len32, 0U);
  return ((Jose_LowStar_Json_Stack_bytes_block){ .buf = dst, .len = len32 });
}

Jose_LowStar_Json_Stack_json_member_u32
Jose_LowStar_Json_Stack_read_member_u32_stack(Jose_LowStar_Json_Stack_json_member_c m)
{
  uint32_t key_len32 = FStar_UInt32_uint_to_t(m.key_len);
  Jose_LowStar_Json_Stack_bytes_block
  u32_key = Jose_LowStar_Json_Stack_read_bytes_with_bound_u32(m.key_buf, key_len32);
  switch (m.value_kind)
  {
    case Jose_LowStar_Json_Stack_JsonValueNull:
      {
        return
          (
            (Jose_LowStar_Json_Stack_json_member_u32){
              .u32_key = u32_key,
              .u32_value_kind = Jose_LowStar_Json_Stack_JsonValueNull,
              .u32_value = { .tag = Jose_LowStar_Json_Stack_BytesBlockNone }
            }
          );
      }
    case Jose_LowStar_Json_Stack_JsonValueString:
      {
        uint32_t value_len32 = FStar_UInt32_uint_to_t(m.value_len);
        Jose_LowStar_Json_Stack_bytes_block
        u32_value_block =
          Jose_LowStar_Json_Stack_read_bytes_with_bound_u32(m.value_buf,
            value_len32);
        return
          (
            (Jose_LowStar_Json_Stack_json_member_u32){
              .u32_key = u32_key,
              .u32_value_kind = Jose_LowStar_Json_Stack_JsonValueString,
              .u32_value = { .tag = Jose_LowStar_Json_Stack_BytesBlockSome, ._0 = u32_value_block }
            }
          );
      }
    default:
      {
        KRML_HOST_EPRINTF("KaRaMeL incomplete match at %s:%d\n", __FILE__, __LINE__);
        KRML_HOST_EXIT(253U);
      }
  }
}

Prims_list__Jose_LowStar_Json_Stack_json_member_u32
*Jose_LowStar_Json_Stack_collect_members_u32_stack(
  Jose_LowStar_Json_Stack_json_member_c *members,
  uint32_t count32
)
{
  return Jose_LowStar_Json_Stack_collect_members_u32_stack_aux(members, count32, 0U);
}
