/*
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /nix/store/yl5jym98klm1y40y6lnsf47c3scqj8dd-karamel-2025-10-08/bin/krml -tmpdir artifacts/karamel -bundle Jose.LowStar.Json.Stack=Jose.LowStar.* -skip-compilation /tmp/tmp.M8KhzUXtzz/out.krml -warn-error -9
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "Jose_Arith_Bounds.h"

#include "internal/Prims.h"
#include "internal/FStar.h"

uint32_t Jose_Arith_Bounds_string_length_to_u32(krml_checked_int_t ctx, Prims_string s)
{
  KRML_MAYBE_UNUSED_VAR(ctx);
  return FStar_UInt32_uint_to_t(FStar_String_strlen(s));
}

uint32_t Jose_Arith_Bounds_nat_to_u32_bounded(krml_checked_int_t ctx, krml_checked_int_t n)
{
  KRML_MAYBE_UNUSED_VAR(ctx);
  return FStar_UInt32_uint_to_t(n);
}

krml_checked_int_t Jose_Arith_Bounds_u32_diff(uint32_t count, uint32_t idx)
{
  return Prims_op_Subtraction(FStar_UInt32_v(count), FStar_UInt32_v(idx));
}
