/*
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /nix/store/yl5jym98klm1y40y6lnsf47c3scqj8dd-karamel-2025-10-08/bin/krml -tmpdir artifacts/karamel -bundle Jose.LowStar.Json.Stack=Jose.LowStar.* -skip-compilation /tmp/tmp.M8KhzUXtzz/out.krml -warn-error -9
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "Jose_Utf8Lemmas.h"

#include "Jose_LowStar_Json_Stack.h"

bool Jose_Utf8Lemmas_uu___is_BufferTooShort(Jose_Utf8Lemmas_decode_error projectee)
{
  if (projectee.tag == Jose_Utf8Lemmas_BufferTooShort)
    return true;
  else
    return false;
}

bool Jose_Utf8Lemmas_uu___is_InvalidKeyEncoding(Jose_Utf8Lemmas_decode_error projectee)
{
  if (projectee.tag == Jose_Utf8Lemmas_InvalidKeyEncoding)
    return true;
  else
    return false;
}

bool Jose_Utf8Lemmas_uu___is_InvalidValueUtf8(Jose_Utf8Lemmas_decode_error projectee)
{
  if (projectee.tag == Jose_Utf8Lemmas_InvalidValueUtf8)
    return true;
  else
    return false;
}

bool Jose_Utf8Lemmas_uu___is_UnknownKey(Jose_Utf8Lemmas_decode_error projectee)
{
  if (projectee.tag == Jose_Utf8Lemmas_UnknownKey)
    return true;
  else
    return false;
}

bool Jose_Utf8Lemmas_uu___is_PolicyViolation(Jose_Utf8Lemmas_decode_error projectee)
{
  if (projectee.tag == Jose_Utf8Lemmas_PolicyViolation)
    return true;
  else
    return false;
}
