/*
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /nix/store/yl5jym98klm1y40y6lnsf47c3scqj8dd-karamel-2025-10-08/bin/krml -tmpdir artifacts/karamel -bundle Jose.LowStar.Json.Stack=Jose.LowStar.* -skip-compilation /tmp/tmp.M8KhzUXtzz/out.krml -warn-error -9
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "JoseNatLemmas.h"

#include "internal/Prims.h"

krml_checked_int_t JoseNatLemmas_nat_sub(krml_checked_int_t x, krml_checked_int_t y)
{
  return Prims_op_Subtraction(x, y);
}
