/*
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /nix/store/yl5jym98klm1y40y6lnsf47c3scqj8dd-karamel-2025-10-08/bin/krml -tmpdir artifacts/karamel -bundle Jose.LowStar.Json.Stack=Jose.LowStar.* -skip-compilation /tmp/tmp.M8KhzUXtzz/out.krml -warn-error -9
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef Jose_Utf8Lemmas_H
#define Jose_Utf8Lemmas_H

#include "krmllib.h"

#include "Jose_LowStar_Json_Stack.h"

#define Jose_Utf8Lemmas_BufferTooShort 0
#define Jose_Utf8Lemmas_InvalidKeyEncoding 1
#define Jose_Utf8Lemmas_InvalidValueUtf8 2
#define Jose_Utf8Lemmas_UnknownKey 3
#define Jose_Utf8Lemmas_PolicyViolation 4

typedef uint8_t Jose_Utf8Lemmas_decode_error_tags;

typedef struct Jose_Utf8Lemmas_decode_error_s
{
  Jose_Utf8Lemmas_decode_error_tags tag;
  union {
    Prims_string case_UnknownKey;
    Prims_string case_PolicyViolation;
  }
  ;
}
Jose_Utf8Lemmas_decode_error;

bool Jose_Utf8Lemmas_uu___is_BufferTooShort(Jose_Utf8Lemmas_decode_error projectee);

bool Jose_Utf8Lemmas_uu___is_InvalidKeyEncoding(Jose_Utf8Lemmas_decode_error projectee);

bool Jose_Utf8Lemmas_uu___is_InvalidValueUtf8(Jose_Utf8Lemmas_decode_error projectee);

bool Jose_Utf8Lemmas_uu___is_UnknownKey(Jose_Utf8Lemmas_decode_error projectee);

bool Jose_Utf8Lemmas_uu___is_PolicyViolation(Jose_Utf8Lemmas_decode_error projectee);

extern krml_checked_int_t Jose_Utf8Lemmas_pow2_8;

extern krml_checked_int_t Jose_Utf8Lemmas_utf8_head_1_max;

extern krml_checked_int_t Jose_Utf8Lemmas_utf8_head_2;

extern krml_checked_int_t Jose_Utf8Lemmas_utf8_head_3;

extern krml_checked_int_t Jose_Utf8Lemmas_utf8_head_4;

extern krml_checked_int_t Jose_Utf8Lemmas_utf8_cont_base;

extern uint8_t Jose_Utf8Lemmas_mk_u8(krml_checked_int_t n);

extern krml_checked_int_t Jose_Utf8Lemmas_byte_val(uint8_t uu___);

extern bool
Jose_Utf8Lemmas_between(
  krml_checked_int_t uu___,
  krml_checked_int_t uu___1,
  krml_checked_int_t uu___2
);

extern bool Jose_Utf8Lemmas_is_cont(uint8_t uu___);

extern bool Jose_Utf8Lemmas_ascii_byte(uint8_t uu___);

extern FStar_Char_char Jose_Utf8Lemmas_ascii_byte_to_char(uint8_t b);

typedef struct Prims_list__uint8_t_s Prims_list__uint8_t;

typedef struct Prims_list__uint8_t_s
{
  Prims_list__Jose_LowStar_Json_Stack_json_member_u32_tags tag;
  uint8_t hd;
  Prims_list__uint8_t *tl;
}
Prims_list__uint8_t;

extern bool Jose_Utf8Lemmas_valid_utf8_bytes(Prims_list__uint8_t *uu___);

extern bool Jose_Utf8Lemmas_canonical_utf8_scalar(Prims_list__uint8_t *uu___);

extern bool Jose_Utf8Lemmas_is_valid_scalar(krml_checked_int_t uu___);

extern Prims_list__uint8_t *Jose_Utf8Lemmas_encode_utf8_codepoint(krml_checked_int_t cp);

extern Prims_list__uint8_t *Jose_Utf8Lemmas_encode_utf8_scalar(FStar_Char_char uu___);

typedef struct Prims_list__FStar_Char_char_s Prims_list__FStar_Char_char;

typedef struct Prims_list__FStar_Char_char_s
{
  Prims_list__Jose_LowStar_Json_Stack_json_member_u32_tags tag;
  FStar_Char_char hd;
  Prims_list__FStar_Char_char *tl;
}
Prims_list__FStar_Char_char;

extern Prims_list__uint8_t
*Jose_Utf8Lemmas_encode_utf8_bytes_aux(Prims_list__FStar_Char_char *uu___);

extern Prims_list__uint8_t *Jose_Utf8Lemmas_encode_utf8_bytes(Prims_string uu___);

#define FStar_Pervasives_Native_None 0
#define FStar_Pervasives_Native_Some 1

typedef uint8_t FStar_Pervasives_Native_option__krml_checked_int_t_tags;

typedef struct FStar_Pervasives_Native_option__krml_checked_int_t_s
{
  FStar_Pervasives_Native_option__krml_checked_int_t_tags tag;
  krml_checked_int_t v;
}
FStar_Pervasives_Native_option__krml_checked_int_t;

extern FStar_Pervasives_Native_option__krml_checked_int_t
Jose_Utf8Lemmas_decode_utf8_scalar_nat(Prims_list__uint8_t *uu___);

#define Jose_Utf8Lemmas_Ok 0
#define Jose_Utf8Lemmas_Error 1

typedef uint8_t
Jose_Utf8Lemmas_jlresult__Prims_list_FStar_Char_char_Jose_Utf8Lemmas_decode_error_tags;

typedef struct
Jose_Utf8Lemmas_jlresult__Prims_list_FStar_Char_char_Jose_Utf8Lemmas_decode_error_s
{
  Jose_Utf8Lemmas_jlresult__Prims_list_FStar_Char_char_Jose_Utf8Lemmas_decode_error_tags tag;
  union {
    Prims_list__FStar_Char_char *case_Ok;
    Jose_Utf8Lemmas_decode_error case_Error;
  }
  ;
}
Jose_Utf8Lemmas_jlresult__Prims_list_FStar_Char_char_Jose_Utf8Lemmas_decode_error;

extern Jose_Utf8Lemmas_jlresult__Prims_list_FStar_Char_char_Jose_Utf8Lemmas_decode_error
Jose_Utf8Lemmas_decode_utf8_chars(Prims_list__uint8_t *uu___);

typedef struct Jose_Utf8Lemmas_jlresult__Prims_string_Jose_Utf8Lemmas_decode_error_s
{
  Jose_Utf8Lemmas_jlresult__Prims_list_FStar_Char_char_Jose_Utf8Lemmas_decode_error_tags tag;
  union {
    Prims_string case_Ok;
    Jose_Utf8Lemmas_decode_error case_Error;
  }
  ;
}
Jose_Utf8Lemmas_jlresult__Prims_string_Jose_Utf8Lemmas_decode_error;

extern Jose_Utf8Lemmas_jlresult__Prims_string_Jose_Utf8Lemmas_decode_error
Jose_Utf8Lemmas_decode_utf8_bytes(Prims_list__uint8_t *uu___);

extern Jose_Utf8Lemmas_jlresult__Prims_string_Jose_Utf8Lemmas_decode_error
Jose_Utf8Lemmas_decode_utf8(Prims_list__uint8_t *uu___);


#define Jose_Utf8Lemmas_H_DEFINED
#endif /* Jose_Utf8Lemmas_H */
