#!/usr/bin/env python3
"""Generate the claim-index.md verification quality report.

Parses spec/compliance-matrix.yaml and produces a Markdown document with
proof-quality and strength breakdowns.  Used in CI (--check mode) to ensure
the committed claim-index.md matches the current matrix.
"""

from __future__ import annotations

import argparse
import pathlib
import sys
from collections import Counter, defaultdict
from datetime import UTC, datetime
from typing import Any, cast

import yaml

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from proof_classification import (
    EMPIRICAL_TYPES,
    FORMAL_TYPES,
    compute_proof_quality,
    compute_strength,
)

MATRIX_FILE = pathlib.Path("spec/compliance-matrix.yaml")
DEFAULT_OUTPUT = pathlib.Path("docs/verification/claims/claim-index.md")

QUALITY_ORDER = {"formal": 0, "empirical": 1, "unknown": 2}
STRENGTH_ORDER = {"lemma": 0, "refinement": 1, "semantic": 2}


def _max_quality(proofs: list[dict[str, Any]]) -> str:
    best = "unknown"
    for p in proofs:
        q = compute_proof_quality(p.get("type", ""))
        if QUALITY_ORDER.get(q, 99) < QUALITY_ORDER.get(best, 99):
            best = q
    return best


def _max_strength(proofs: list[dict[str, Any]]) -> str:
    best = "semantic"
    for p in proofs:
        s = compute_strength(p)
        if STRENGTH_ORDER.get(s, 99) < STRENGTH_ORDER.get(best, 99):
            best = s
    return best


def _spec_label(key: str) -> str:
    """Convert a YAML key like 'rfc_6749' to 'RFC 6749'."""
    if key.startswith("rfc_"):
        return "RFC " + key[4:].replace("_", " ").upper().split()[0]
    if key.startswith("draft_"):
        return "draft-" + key[6:].replace("_", "-")
    if key.startswith("openid_"):
        return "OIDC " + key[7:].replace("_", " ").title()
    return key.replace("_", " ").title()


def generate(data: dict[str, object]) -> str:
    """Generate the claim-index Markdown content."""
    lines: list[str] = []

    # Collect all entries (all statuses) and verified entries
    all_entries: list[tuple[str, dict[str, Any]]] = []
    verified_entries: list[tuple[str, dict[str, Any]]] = []

    for key, entries in data.items():
        if key == "metadata":
            continue
        if not isinstance(entries, list):
            continue
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            all_entries.append((key, entry))
            if entry.get("status") == "verified":
                verified_entries.append((key, entry))

    # Proof block stats (on verified entries only)
    total_proof_blocks = 0
    quality_block_counts: Counter[str] = Counter()
    strength_block_counts: Counter[str] = Counter()
    type_strength: dict[str, Counter[str]] = defaultdict(Counter)

    for _key, entry in verified_entries:
        for p in entry.get("proof", []):
            total_proof_blocks += 1
            q = compute_proof_quality(p.get("type", ""))
            quality_block_counts[q] += 1
            s = compute_strength(p)
            strength_block_counts[s] += 1
            ptype = p.get("type", "unknown")
            type_strength[ptype][s] += 1

    # Entry-level stats
    entry_quality_counts: Counter[str] = Counter()
    entry_strength_counts: Counter[str] = Counter()
    for _key, entry in verified_entries:
        raw_proofs = entry.get("proof", [])
        proofs = (
            [proof for proof in raw_proofs if isinstance(proof, dict)]
            if isinstance(raw_proofs, list)
            else []
        )
        entry_quality_counts[_max_quality(proofs)] += 1
        entry_strength_counts[_max_strength(proofs)] += 1

    # Header
    generated_at = datetime.now(UTC)
    today = generated_at.strftime("%Y-%m-%d")
    now = generated_at.strftime("%Y-%m-%d %H:%M UTC")
    lines.append("# Claim Index — Verification Quality Report")
    lines.append("")
    lines.append(f"Last updated: {today}")
    lines.append("")
    lines.append("Status: snapshot")
    lines.append("")
    lines.append("Owner: Verification")
    lines.append("")
    lines.append("Audience: verification reviewers, maintainers")
    lines.append("")
    lines.append(
        f"> **Status note ({today}):** Machine-generated snapshot; rerun this "
        "generator before using it for a new verification review."
    )
    lines.append("")
    lines.append("<!-- AUTO-GENERATED by generate_claim_index.py -- DO NOT EDIT -->")
    lines.append(f"<!-- Generated: {now} -->")
    lines.append("")
    lines.append("This document provides a machine-generated breakdown of proof quality")
    lines.append("and evidence strength for all `status: verified` entries in the")
    lines.append("[compliance matrix](../../../spec/compliance-matrix.yaml).")
    lines.append("")
    lines.append(
        "See [assurance-case/verification-scope.md §1.6]"
        "(assurance-case/verification-scope.md#16-proof-quality-classification)"
    )
    lines.append("for quality/strength definitions.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # 1. Summary
    lines.append("## 1. Summary")
    lines.append("")
    lines.append("| Metric | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| Total entries (all statuses) | {len(all_entries)} |")
    lines.append(f"| Verified entries | {len(verified_entries)} |")
    lines.append(f"| Proof blocks (on verified entries) | {total_proof_blocks} |")
    lines.append("")

    # 2. Proof Quality
    lines.append("## 2. Proof Quality Breakdown")
    lines.append("")
    lines.append("| Quality | Proof Blocks | Entries (max) |")
    lines.append("|---------|-------------|---------------|")
    for q in ["formal", "empirical", "unknown"]:
        bc = quality_block_counts.get(q, 0)
        ec = entry_quality_counts.get(q, 0)
        lines.append(f"| {q} | {bc} | {ec} |")
    lines.append("")

    # 3. Proof Strength
    lines.append("## 3. Proof Strength Breakdown")
    lines.append("")
    lines.append("| Strength | Proof Blocks | Entries (max) |")
    lines.append("|----------|-------------|---------------|")
    for s in ["lemma", "refinement", "semantic"]:
        bc = strength_block_counts.get(s, 0)
        ec = entry_strength_counts.get(s, 0)
        lines.append(f"| {s} | {bc} | {ec} |")
    lines.append("")

    # 4. By Verification Type
    lines.append("## 4. Strength by Verification Type")
    lines.append("")
    lines.append("| Type | Lemma | Refinement | Semantic | Total |")
    lines.append("|------|-------|------------|----------|-------|")

    all_types = sorted(FORMAL_TYPES | EMPIRICAL_TYPES)
    # Add any other types that appear
    for t in sorted(type_strength.keys()):
        if t not in all_types:
            all_types.append(t)

    for t in all_types:
        counts = type_strength.get(t, Counter())
        le = counts.get("lemma", 0)
        re_ = counts.get("refinement", 0)
        se = counts.get("semantic", 0)
        total = le + re_ + se
        if total > 0:
            lines.append(f"| `{t}` | {le} | {re_} | {se} | {total} |")
    lines.append("")

    # 5. Per-Entry Detail (with Runtime Link column)
    lines.append("## 5. Per-Entry Detail")
    lines.append("")
    lines.append("| ID | Spec | Max Quality | Max Strength | Proof Types | Runtime Link |")
    lines.append("|----|------|-------------|--------------|-------------|--------------|")

    # Sort by spec key then ID
    sorted_entries = sorted(verified_entries, key=lambda x: (x[0], x[1].get("id", "")))
    for key, entry in sorted_entries:
        eid = entry.get("id", "?")
        spec = _spec_label(key)
        raw_proofs = entry.get("proof", [])
        proofs = (
            [proof for proof in raw_proofs if isinstance(proof, dict)]
            if isinstance(raw_proofs, list)
            else []
        )
        mq = _max_quality(proofs)
        ms = _max_strength(proofs)
        ptypes = sorted({p.get("type", "?") for p in proofs})
        rl = entry.get("runtime_link", "")
        rl_display = pathlib.PurePosixPath(rl).name if rl else "-"
        lines.append(f"| {eid} | {spec} | {mq} | {ms} | {', '.join(ptypes)} | {rl_display} |")

    lines.append("")

    # 6. Runtime Linkage
    lines.append("## 6. Runtime Linkage")
    lines.append("")

    with_rl = sum(1 for _, e in verified_entries if e.get("runtime_link"))
    without_rl = len(verified_entries) - with_rl

    # Categorize by module prefix (how the link was derived)
    rl_categories: Counter[str] = Counter()
    rl_files: set[str] = set()
    for _, entry in verified_entries:
        rl = entry.get("runtime_link", "")
        if not rl:
            continue
        rl_files.add(rl)
        module = entry.get("module", "")
        if module.startswith("crates/"):
            rl_categories["Rust direct"] += 1
        elif module.startswith("fstar/"):
            rl_categories["F* mapped"] += 1
        elif module.startswith("docs/"):
            rl_categories["Docs mapped"] += 1
        else:
            rl_categories["Other"] += 1

    lines.append("| Metric | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| Entries with runtime_link | {with_rl} |")
    lines.append(f"| Entries without runtime_link | {without_rl} |")
    lines.append(f"| Distinct runtime files | {len(rl_files)} |")
    lines.append("")

    lines.append("| Category | Entries |")
    lines.append("|----------|---------|")
    for cat in ["Rust direct", "F* mapped", "Docs mapped", "Other"]:
        count = rl_categories.get(cat, 0)
        if count > 0:
            lines.append(f"| {cat} | {count} |")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare output with existing file; exit 1 if mismatch",
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=DEFAULT_OUTPUT,
        help=f"Output file path (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args()

    if not MATRIX_FILE.exists():
        print(f"ERROR: {MATRIX_FILE} not found", file=sys.stderr)
        return 1

    data = cast("dict[str, object]", yaml.safe_load(MATRIX_FILE.read_text()))
    content = generate(data)

    if args.check:
        if not args.output.exists():
            print(
                f"ERROR: {args.output} does not exist (run without --check first)",
                file=sys.stderr,
            )
            return 1

        existing = args.output.read_text()

        # Strip the timestamp line for comparison (it changes every run)
        def strip_timestamp(text: str) -> str:
            return "\n".join(
                line
                for line in text.splitlines()
                if not line.startswith(("Last updated:", "<!-- Generated:", "> **Status note ("))
            )

        if strip_timestamp(existing) != strip_timestamp(content):
            print(f"ERROR: {args.output} is out of date. Regenerate with:", file=sys.stderr)
            print(f"  python3 {__file__}", file=sys.stderr)
            return 1

        print(f"OK: {args.output} is up to date")
        return 0

    # Write output
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content)
    print(f"Generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
