//! Independent admission field inventory shared by signed and ordinary tests.
pub(crate) const OP_ARRAYS: &[&str] = &[
    "scopes_supported",
    "response_types_supported",
    "response_modes_supported",
    "grant_types_supported",
    "acr_values_supported",
    "subject_types_supported",
    "id_token_signing_alg_values_supported",
    "id_token_encryption_alg_values_supported",
    "id_token_encryption_enc_values_supported",
    "userinfo_signing_alg_values_supported",
    "userinfo_encryption_alg_values_supported",
    "userinfo_encryption_enc_values_supported",
    "request_object_signing_alg_values_supported",
    "request_object_encryption_alg_values_supported",
    "request_object_encryption_enc_values_supported",
    "token_endpoint_auth_methods_supported",
    "token_endpoint_auth_signing_alg_values_supported",
    "display_values_supported",
    "claim_types_supported",
    "claims_supported",
    "claims_locales_supported",
    "ui_locales_supported",
    "revocation_endpoint_auth_methods_supported",
    "revocation_endpoint_auth_signing_alg_values_supported",
    "introspection_endpoint_auth_methods_supported",
    "introspection_endpoint_auth_signing_alg_values_supported",
    "code_challenge_methods_supported",
    "dpop_signing_alg_values_supported",
    "aegaeon_access_token_formats_supported",
];
pub(crate) const AS_ARRAYS: &[&str] = &[
    "scopes_supported",
    "response_types_supported",
    "response_modes_supported",
    "grant_types_supported",
    "token_endpoint_auth_methods_supported",
    "token_endpoint_auth_signing_alg_values_supported",
    "ui_locales_supported",
    "revocation_endpoint_auth_methods_supported",
    "revocation_endpoint_auth_signing_alg_values_supported",
    "introspection_endpoint_auth_methods_supported",
    "introspection_endpoint_auth_signing_alg_values_supported",
    "code_challenge_methods_supported",
    "dpop_signing_alg_values_supported",
];
pub(crate) const OP_BOOLEANS: &[&str] = &[
    "claims_parameter_supported",
    "request_parameter_supported",
    "request_uri_parameter_supported",
    "require_request_uri_registration",
    "require_pushed_authorization_requests",
    "require_signed_request_object",
    "authorization_response_iss_parameter_supported",
    "tls_client_certificate_bound_access_tokens",
];
pub(crate) const AS_BOOLEANS: &[&str] = &[
    "require_pushed_authorization_requests",
    "require_signed_request_object",
    "authorization_response_iss_parameter_supported",
    "tls_client_certificate_bound_access_tokens",
];
pub(crate) const AUTH_ARRAYS: &[&str] = &[
    "token_endpoint_auth_signing_alg_values_supported",
    "revocation_endpoint_auth_signing_alg_values_supported",
    "introspection_endpoint_auth_signing_alg_values_supported",
];
